### ISSUE TITLE
I cannot see the animation when use javascript in web maker?

### ISSUE THREAD

**Issue by ridergoku** [chinchang/web-maker#281]
when make onclick function to show alert, it doesn't work!

**Comment by chinchang** [comment]
Inline JavaScript is not allowed in Chrome extension due to security policies. So if you want to use Chrome extension, write JavaScript in JS panel. Eg.
`document.querySelector('#someid').addEventListener('click', function() { });`

Or else, use the web app -> https://webmakerapp.com/app/
No such restriction there.

Closing issue. Do open again if any doubt.
