### ISSUE TITLE
web maker won't load one of my libraries

### ISSUE THREAD

**Issue by dkuku** [chinchang/web-maker#302]
I'm following a online js course and it's done in jsbin, I wanted to run it in web maker but it's not loading this library which works everywhere else (codepen and jsbin):
https://cdn.rawgit.com/knowthen/d90da7fbbcc3222252d2845eef2adc38/raw/6099003c3102daf281681cd92b7158477a1bc5f4/hyperscript-browser.js
when i clicked at the bottom of webmaker: open in codepen my code run without any changes, straight from webmaker. Thats the pen
web maker just throws error on the line where I want to use this library:
 ReferenceError: tags is not defined
    at script 5:13 

https://codepen.io/dkuku/pen/JZYVZN?editors=0010

**Comment by chinchang** [comment]
Hi @dkuku 
The issue is that in the Chrome extension, JavaScript can only be loaded from the whitelisted domains. And `cdn.rawgit.com` isn't listed at the moment. I'll add it to the list.

But I'll recommend you switch to the web app -> https://webmakerapp.com/app/. It works same, works offline too! And there are no such restrictions also :)
