### ISSUE TITLE
Fix CSP error in chrome canary

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#39]
Seems like from chrome 57, extension's CSP applies on the iframe open in the extension too. It does not apply before that version.

Issues:

- Inline scripts wont work which was used to run user's js
- remote scripts can't be fetched (required to load external libs)

**Comment by chinchang** [comment]
This has been fixed. As a solution, from now you can only add external JavaScript libraries from selected domains only (the ones listed in the add library modal). All popular CDNs are listed there. But if you come across a domain that should be added, please comment here and I'll add it.

**Comment by xt0rted** [comment]
I'm not sure if this should be added, but Stripe offers [Elements](https://stripe.com/docs/elements) which is UI controls you can add to your forms to capture the payment info. This requires referencing `https://js.stripe.com/v3/` in order to create them. I tried mocking up a payment form with this but couldn't because of the CSP error.

**Comment by chinchang** [comment]
@xt0rted Seems like stripe's JS can't even be loaded from CDNs. I have added it to the list of allowed domains and its live in v2.4.3. Please update your extension and it should work fine :)

**Comment by xt0rted** [comment]
@chinchang it works now. Thanks!
