### ISSUE TITLE
improve add library with esm or systemjs

### ISSUE THREAD

**Issue by joebnb** [chinchang/web-maker#521]
i think it should be better than just add umd library in dom

**Comment by Shaxine** [comment]
Apologies if this issue is outdated or unrelated. After searching, I couldn't find a way to import ESM modules. Inserting the path in `Add Library` has no effect, and adding the import at the start of the `JS` code results in this error: `Uncaught SyntaxError: import declarations may only appear at top level of a module.`

Is there a known workaround for importing ESM modules?

**Comment by chinchang** [comment]
Hi @Shaxine! There was no ESM module support....uptil now :)
I just hacked a quick thing. Now, if you JS has `import` statements, ESM mode is auto-switched on. You should now be able to import scripts. Here's a demo:

![CleanShot 2024-09-02 at 23 54 52](https://github.com/user-attachments/assets/900dad1d-60e9-42c8-9bc3-a02112eb4e56)
