### ISSUE TITLE
Add optional themes for the editor

### ISSUE THREAD

**Issue by chinchang** [chinchang/web-maker#84]
Codemirror themes https://codemirror.net/demo/theme.html

**Comment by jordannakamoto** [comment]
hey friend, thank you so much for this tool and the open sourcing. Here is what my hack looks like:

http://i.imgur.com/06PoeTt.png
I think replacing the default scrollbar with the webkit one is really important... and I'm going to edit my font colors soon. Also I took out the logo link to your website (after thoroughly checking it out!) but I would put it at opacity .2 or something like that because it's kind of distracting.

I would consider somehow implementing a font picker like this(my font is Lekton) :
http://app.programmingfonts.org/#input

**Comment by jordannakamoto** [comment]
Hey I also noticed that in my copy the --code-font-size for .Codemirror class is getting overwritten... so i just put an !important but there's probably a better way to do it

**Comment by chinchang** [comment]
This is live in v2.4.

@jordannakamoto That programming font list is great, I'll surely add that. And I also made the logo more subtle in v2.4 :) Thanks for the suggestions.
